# Generated by Django 2.0 on 2018-12-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UsersData'},
        ),
    ]
