# Generated by Django 2.0 on 2018-12-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liker', '0003_auto_20181231_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'User data', 'verbose_name_plural': "User's data"},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='login',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=58, null=True),
        ),
    ]
